// Custom hooks barrel export
export { useAuth, AuthProvider } from "./useAuth"
export { useDebounce } from "./useDebounce"
export { useSearch } from "./useSearch"
export { useAdvancedSearch } from "./useAdvancedSearch"
export { useItems } from "./useItems"
export { useItem, useUpdateItem, useDeleteItem, useCreateItem, useMoveItem, useAdjustStock } from "./useItem"
export { useItemHistory } from "./useItemHistory"
export { useItemRelationships } from "./useItemRelationships"
export { useLocations, useLocation, useLocationContents, useLocationTree, useCreateLocation, useUpdateLocation } from "./useLocations"
export { useSavedViews, useCreateSavedView, useDeleteSavedView } from "./useSavedViews"
export type { SavedViewResponse } from "./useSavedViews"
export { useScan } from "./useScan"
export type { ScanResult } from "./useScan"
export { useUploadMedia, useDeleteMedia, useSetPrimaryMedia } from "./useMedia"
export type { MediaResponse } from "./useMedia"
export { useCategories, useCreateCategory, useUpdateCategory, useAddItemCategory, useRemoveItemCategory } from "./useCategories"
export type { CategoryResponse } from "./useCategories"
export { useTags, useCreateTag, useAddItemTag, useRemoveItemTag, useAddLocationTag, useRemoveLocationTag } from "./useTags"
export type { TagResponse } from "./useTags"
