"""initial_schema

Revision ID: 205b045a4c4a
Revises: 
Create Date: 2026-03-25 20:00:12.507840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '205b045a4c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pg_trgm extension for trigram fuzzy matching
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_categories_slug'), 'item_categories', ['slug'], unique=True)
    op.create_table('label_records',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('label_code', sa.String(length=50), nullable=False),
    sa.Column('qr_payload', sa.String(length=500), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_records_entity_id'), 'label_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_label_records_entity_type'), 'label_records', ['entity_type'], unique=False)
    op.create_table('locations',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_location_id', sa.UUID(), nullable=True),
    sa.Column('path_text', sa.String(length=2000), nullable=True),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_table('media_assets',
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_owner_id'), 'media_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_type'), 'media_assets', ['owner_type'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'Editor', 'Viewer', 'API_Client', name='user_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('items',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.Enum('Consumable', 'Equipment', 'Component', 'Tool', 'Container', 'Kit', 'Documented_Reference', name='item_type', native_enum=False), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_container', sa.Boolean(), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('is_serialized', sa.Boolean(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model_number', sa.String(length=255), nullable=True),
    sa.Column('part_number', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.Enum('Available', 'In_Use', 'Loaned_Out', 'Needs_Repair', 'Retired', name='item_condition', native_enum=False), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('quantity_mode', sa.String(length=50), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('minimum_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_source', sa.String(length=500), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('calibration_due_date', sa.Date(), nullable=True),
    sa.Column('maintenance_due_date', sa.Date(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_index('ix_items_model_number_trgm', 'items', ['model_number'], unique=False, postgresql_using='gin', postgresql_ops={'model_number': 'gin_trgm_ops'})
    op.create_index('ix_items_name_trgm', 'items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_items_normalized_name'), 'items', ['normalized_name'], unique=False)
    op.create_index('ix_items_search_vector', 'items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('location_tags',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'tag_id')
    )
    op.create_table('saved_views',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('filter_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_views_user_id'), 'saved_views', ['user_id'], unique=False)
    op.create_table('item_placements',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('parent_item_id', sa.UUID(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placement_type', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('location_id IS NOT NULL OR parent_item_id IS NOT NULL', name='ck_placement_has_destination'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_placements_item_id'), 'item_placements', ['item_id'], unique=False)
    op.create_table('item_relationships',
    sa.Column('source_item_id', sa.UUID(), nullable=False),
    sa.Column('target_item_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('accessory_of', 'spare_part_for', 'compatible_with', 'belongs_to_kit', 'manual_for', name='relationship_type', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_relationships_source_item_id'), 'item_relationships', ['source_item_id'], unique=False)
    op.create_index(op.f('ix_item_relationships_target_item_id'), 'item_relationships', ['target_item_id'], unique=False)
    op.create_table('item_tags',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('stock_transactions',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('add', 'consume', 'adjust', 'count', 'dispose', 'return_', name='transaction_type', native_enum=False), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('resulting_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transactions_item_id'), 'stock_transactions', ['item_id'], unique=False)
    # ### end Alembic commands ###

    # Create trigger function to auto-update search_vector on items
    op.execute("""
        CREATE OR REPLACE FUNCTION items_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.name, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.description, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.notes, '')), 'C') ||
                setweight(to_tsvector('english', coalesce(NEW.brand, '')), 'C') ||
                setweight(to_tsvector('english', coalesce(NEW.model_number, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.part_number, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.serial_number, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER items_search_vector_trigger
        BEFORE INSERT OR UPDATE ON items
        FOR EACH ROW EXECUTE FUNCTION items_search_vector_update();
    """)


def downgrade() -> None:
    # Drop search vector trigger and function
    op.execute("DROP TRIGGER IF EXISTS items_search_vector_trigger ON items")
    op.execute("DROP FUNCTION IF EXISTS items_search_vector_update()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transactions_item_id'), table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_table('item_tags')
    op.drop_index(op.f('ix_item_relationships_target_item_id'), table_name='item_relationships')
    op.drop_index(op.f('ix_item_relationships_source_item_id'), table_name='item_relationships')
    op.drop_table('item_relationships')
    op.drop_index(op.f('ix_item_placements_item_id'), table_name='item_placements')
    op.drop_table('item_placements')
    op.drop_index(op.f('ix_saved_views_user_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_table('location_tags')
    op.drop_index('ix_items_search_vector', table_name='items', postgresql_using='gin')
    op.drop_index(op.f('ix_items_normalized_name'), table_name='items')
    op.drop_index('ix_items_name_trgm', table_name='items', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_items_model_number_trgm', table_name='items', postgresql_using='gin', postgresql_ops={'model_number': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_media_assets_owner_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_owner_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_label_records_entity_type'), table_name='label_records')
    op.drop_index(op.f('ix_label_records_entity_id'), table_name='label_records')
    op.drop_table('label_records')
    op.drop_index(op.f('ix_item_categories_slug'), table_name='item_categories')
    op.drop_table('item_categories')
    # ### end Alembic commands ###

    # Drop pg_trgm extension
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
